export const mockEvents = [
  {
    id: 1,
    name: "Vonage API Workshop",
    event_type: "workshop",
    permission: "private",
    start_time: 1610442000000,
    end_time: 1610443800000,
    description:
      "A Nanoleaf Shapes Mini Triangle Smarter Kit will be awarded to each member of the winning team for Best Use of Vonage API. Vonage is a cloud communications platform that allows developers to integrate voice, video and messaging into their applications using their communication APIs. So whether you want to build video calls into your app, create a Facebook bot, or build applications on top of programmable phone numbers, Vonage has got you covered",
    speakers: [{ name: "Vonage" }],
    public_url: "",
    private_url: "https://hopin.com/events/hack-the-north-2020",
    related_events: [2, 3],
  },
  {
    id: 2,
    name: "Intro to React",
    event_type: "workshop",
    permission: "private",
    start_time: Date.now() + 3600000,
    end_time: Date.now() + 7200000,
    description: "Learn the basics of React in this hands-on workshop.",
    speakers: [{ name: "Jane Doe" }],
    private_url: "https://example.com/react-workshop",
    related_events: [1],
  },
  {
    id: 3,
    name: "AI Ethics Panel",
    event_type: "tech_talk",
    permission: "public",
    start_time: Date.now() + 10800000,
    end_time: Date.now() + 14400000,
    description: "Discussing the ethical implications of AI in today's world.",
    speakers: [{ name: "John Smith" }, { name: "Alice Johnson" }],
    public_url: "https://example.com/ai-ethics-public",
    private_url: "https://example.com/ai-ethics-private",
    related_events: [1, 4, 5, 6, 7],
  },
  {
    id: 4,
    name: "Building ML Models",
    event_type: "workshop",
    permission: "private",
    start_time: Date.now() + 18000000,
    end_time: Date.now() + 21600000,
    description:
      "Hands-on workshop on building and training machine learning models using PyTorch.",
    speakers: [{ name: "Maria Garcia" }, { name: "Steve Wilson" }],
    private_url: "https://example.com/ml-workshop",
    related_events: [3, 5],
  },
  {
    id: 5,
    name: "Startup Founder Panel",
    event_type: "tech_talk",
    permission: "public",
    start_time: Date.now() + 25200000,
    end_time: Date.now() + 28800000,
    description:
      "Learn from successful startup founders about their entrepreneurial journey.",
    speakers: [
      { name: "Mark Thompson" },
      { name: "Sarah Lee" },
      { name: "David Chen" },
    ],
    public_url: "https://example.com/startup-panel-public",
    private_url: "https://example.com/startup-panel-private",
    related_events: [6],
  },
  {
    id: 6,
    name: "Hackathon Game Night",
    event_type: "activity",
    permission: "public",
    start_time: Date.now() + 32400000,
    end_time: Date.now() + 36000000,
    description:
      "Take a break and join us for a fun night of virtual games and networking!",
    speakers: [{ name: "Gaming Committee" }],
    public_url: "https://example.com/game-night-public",
    private_url: "https://example.com/game-night-private",
    related_events: [5],
  },
];
