export const mockEvents = [
  {
    id: 1,
    name: "Vonage API Workshop",
    event_type: "workshop",
    permission: "private",
    start_time: 1610442000000,
    end_time: 1610443800000,
    description:
      "A Nanoleaf Shapes Mini Triangle Smarter Kit will be awarded to each member of the winning team for Best Use of Vonage API. Vonage is a cloud communications platform that allows developers to integrate voice, video and messaging into their applications using their communication APIs. So whether you want to build video calls into your app, create a Facebook bot, or build applications on top of programmable phone numbers, Vonage has got you covered",
    speakers: [{ name: "Vonage" }],
    public_url: "",
    private_url: "https://hopin.com/events/hack-the-north-2020",
    related_events: [2, 3],
  },
  {
    id: 2,
    name: "Intro to React",
    event_type: "workshop",
    permission: "private",
    start_time: Date.now() + 3600000,
    end_time: Date.now() + 7200000,
    description: "Learn the basics of React in this hands-on workshop.",
    speakers: [{ name: "Jane Doe" }],
    private_url: "https://example.com/react-workshop",
    related_events: [1],
  },
  {
    id: 3,
    name: "AI Ethics Panel",
    event_type: "tech_talk",
    permission: "public",
    start_time: Date.now() + 10800000,
    end_time: Date.now() + 14400000,
    description: "Discussing the ethical implications of AI in today's world.",
    speakers: [{ name: "John Smith" }, { name: "Alice Johnson" }],
    public_url: "https://example.com/ai-ethics-public",
    private_url: "https://example.com/ai-ethics-private",
    related_events: [1, 2],
  },
];
